'use client';

import { useState } from 'react';
import styles from './page.module.css';

/**
 * Getting Reef into Nimiq Pay while it is not in the directory.
 *
 * The nimpay.app HTTPS opener is a server-side allowlist and 404s for unlisted
 * apps. The `nimiqpay://` scheme is handled by the app itself and warns rather
 * than blocking, so a plain tappable link is the shortest route onto a device.
 *
 * On a desktop none of that helps — the app is on a phone. The QR is the
 * bridge, and it encodes this page rather than the deep link, because phone
 * cameras routinely refuse to open a custom scheme.
 */
const APP_URL = 'https://reef.nimiq.cafe';
const DEEPLINK = `nimiqpay://miniapp?url=${encodeURIComponent(APP_URL)}`;

export default function OpenInNimiqPay() {
  const [copied, setCopied] = useState(false);

  async function copy() {
    try {
      await navigator.clipboard.writeText(APP_URL);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      setCopied(false);
    }
  }

  return (
    <main className={styles.wrap}>
      <div className={styles.step}>
        <h1 className={styles.title}>Open Reef in Nimiq Pay</h1>
        <p className={styles.sub}>Open this page on the phone that has Nimiq Pay installed.</p>
      </div>

      {/* Static, generated by `npm run qr` and decode-checked there, so it
          costs nothing at runtime and cannot silently stop scanning. */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img className={styles.qr} src="/open-qr.svg" alt="QR code linking to this page" width={200} height={200} />
      <p className={styles.sub}>On a computer? Scan this with the phone that has Nimiq Pay.</p>

      <div className={styles.divider}>or, on the phone itself</div>

      <a className={styles.cta} href={DEEPLINK}>
        Open in Nimiq Pay
      </a>
      <p className={styles.sub}>
        Nimiq Pay will warn that this app is not in its directory. That is expected while it is
        unlisted — continue past it.
      </p>

      <div className={styles.divider}>or paste it manually</div>

      <div className={styles.step}>
        <h2>Mini Apps → Custom URL</h2>
        <p>
          If you cannot see that field, open the app menu and hold the settings button for about ten
          seconds to reveal the developer menu, then look again.
        </p>
        <div className={styles.urlbox}>{APP_URL}</div>
        <button className={styles.copy} onClick={() => void copy()} type="button">
          {copied ? 'Copied' : 'Copy URL'}
        </button>
      </div>
    </main>
  );
}
