'use client';

import { useEffect, useRef, useState } from 'react';
import { inAppBrowser } from '@/lib/nimiq/in-app';
import styles from './page.module.css';

/**
 * Getting Reef into Nimiq Pay while it is not in the directory.
 *
 * The nimpay.app HTTPS opener is a server-side allowlist and 404s for unlisted
 * apps. The `nimiqpay://` scheme is handled by the app itself and warns rather
 * than blocking, so a plain tappable link is the shortest route onto a device.
 *
 * On a desktop none of that helps — the app is on a phone. The QR is the
 * bridge, and it encodes this page rather than the deep link, because phone
 * cameras routinely refuse to open a custom scheme.
 *
 * And a QR is usually scanned by *something*: WeChat, LINE, Instagram. Those
 * open their own in-app browser, which blocks custom schemes outright. This
 * page says so before the tap, and says it again after if nothing happened.
 */

/**
 * In-app browsers that will silently swallow a `nimiqpay://` tap.
 *
 * Sniffing a user agent is a poor tool and the right one here: the thing being
 * detected is the browser itself, and there is no feature test for "will
 * refuse a custom scheme without telling you".
 */
const APP_URL = 'https://reef.nimiq.cafe';
const DEEPLINK = `nimiqpay://miniapp?url=${encodeURIComponent(APP_URL)}`;

export default function OpenInNimiqPay() {
  const [copied, setCopied] = useState(false);
  const [host, setHost] = useState<string | null>(null);
  const [stuck, setStuck] = useState(false);
  const tapped = useRef(false);

  useEffect(() => setHost(inAppBrowser(navigator.userAgent)), []);

  /*
   * If the deep link worked, this page goes to the background. Still visible a
   * moment later means nothing happened — either an in-app browser swallowed
   * it or Nimiq Pay is not installed. Either way the person deserves to be
   * told rather than left tapping a dead button.
   */
  useEffect(() => {
    const onHide = () => {
      if (document.visibilityState === 'hidden') setStuck(false);
    };
    document.addEventListener('visibilitychange', onHide);
    return () => document.removeEventListener('visibilitychange', onHide);
  }, []);

  function tryDeepLink() {
    tapped.current = true;
    window.setTimeout(() => {
      if (tapped.current && document.visibilityState === 'visible') setStuck(true);
    }, 1600);
  }

  async function copy() {
    try {
      await navigator.clipboard.writeText(APP_URL);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      setCopied(false);
    }
  }

  return (
    <main className={styles.wrap}>
      <div className={styles.step}>
        <h1 className={styles.title}>Open Reef in Nimiq Pay</h1>
        <p className={styles.sub}>Open this page on the phone that has Nimiq Pay installed.</p>
      </div>

      {host ? (
        <div className={styles.warn} role="alert">
          <strong>Open this page in your browser first.</strong>
          <span>
            You are in {host}&rsquo;s built-in browser, and it blocks links to other apps — the
            button below will do nothing here. Use the menu (usually &hellip; or &#x22EF;) and
            choose <em>Open in Safari</em> or <em>Open in Chrome</em>.
          </span>
        </div>
      ) : null}

      {/* Static, generated by `npm run qr` and decode-checked there, so it
          costs nothing at runtime and cannot silently stop scanning. */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img className={styles.qr} src="/open-qr.svg" alt="QR code linking to this page" width={200} height={200} />
      <p className={styles.sub}>On a computer? Scan this with the phone that has Nimiq Pay.</p>

      <div className={styles.divider}>or, on the phone itself</div>

      <a className={styles.cta} href={DEEPLINK} onClick={tryDeepLink}>
        Open in Nimiq Pay
      </a>
      {stuck ? (
        <p className={styles.stuck}>
          Nothing happened. Either this browser blocked it — open the page in Safari or Chrome and
          try again — or Nimiq Pay is not installed on this phone.
        </p>
      ) : null}
      <p className={styles.sub}>
        Nimiq Pay will warn that this app is not in its directory. That is expected while it is
        unlisted — continue past it.
      </p>

      <div className={styles.divider}>or paste it manually</div>

      <div className={styles.step}>
        <h2>Mini Apps → Custom URL</h2>
        <p>
          If you cannot see that field, open the app menu and hold the settings button for about ten
          seconds to reveal the developer menu, then look again.
        </p>
        <div className={styles.urlbox}>{APP_URL}</div>
        <button className={styles.copy} onClick={() => void copy()} type="button">
          {copied ? 'Copied' : 'Copy URL'}
        </button>
      </div>
    </main>
  );
}
